version: '3.8'

services:
  log-interpreter-agent:
    build: .
    container_name: log-interpreter-agent
    ports:
      - "3000:3000"
    environment:
      # Required environment variables
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT:-gcp-starter}
      
      # Optional environment variables with defaults
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER:-simple}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-simple}
      - GROQ_MODEL=${GROQ_MODEL:-llama-3.3-70b-versatile}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-log-interpreter-index}
      
      # Node environment
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
    volumes:
      # Persist uploaded files
      - ./uploads:/app/uploads
      # Optional: Mount .env file if you prefer file-based config
      # - ./.env:/app/.env:ro
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: log-interpreter-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   command: redis-server --appendonly yes

# volumes:
#   redis_data:
