server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Collect logs from a simple log file that we'll create
  - job_name: ai-file-reader-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ai-file-reader
          __path__: /var/log/ai-file-reader.log

  # Collect Docker container logs with proper configuration
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["ai-file-reader-*"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_name']
        regex: '/ai-file-reader-(.*)'
        target_label: 'service'
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
